### ISSUE TITLE
Strip out HTML comments

### ISSUE THREAD

**Issue by andkorsh** [tompazourek/RazorHtmlMinifier.Mvc5#7]
Hey @tompazourek, thank you for this thing, absolutely love the idea of compile-time transformation.

Though, do you think it's possible to add an ability to remove `<!-- HTML comments -->` from the outcome as well? I can work on it if you don't want or don't have time - would appreciate if you then accept my pull request and redeploy the lib in Nuget.

Also it would be great if this thing was somehow configurable so that a user can choose whether they want to strip out comments or not, and maybe they don't want newlines at all so they can be completely removed (or replaced with a single space so that nothing breaks). Do you know if any configuration may be read from web.config at the compile time?

Thanks!
Andrew K.

**Comment by andkorsh** [comment]
Actually just read your comment in #4 and it actually makes sense that no one should use HTML comments in CSHTML files so I may just replace all existing comments with Razor ones and then force all the developers to only use those. Also there's a place where we use `<!--[if mso]>` which shouldn't be stripped which makes the logic even more complicated, so probably can close the ticket. Stripping newlines can still be useful though if we have a way to configure the minification.

**Comment by tompazourek** [comment]
Hey @andkorsh, the newlines might actually be significant, so we cannot just easily strip them out.

Consider the following HTML:

```
Hello
world
```

It gets rendered as `Hello world` in the browser. If we'd strip newlines, it'd get rendered as `Helloworld`.

You might argue that a newline is two bytes (`\r\n`) where it can be shortened just to a space ` ` (one byte). The library actually shortens the Windows-like `\r\n` endings to Unix-like `\n` endings, so the result is still one byte. That means that the minified result is as short as it would be if we replaced newlines with spaces, but it's closer to the original.

What the library also tries to do is to minify consecutive sequence of whitespace or newlines to a single byte (either a `\n` or ` `). It's still not working 100% perfectly (I am not completely sure why), but a lot of the whitespace gets stripped out.
